# Generated by Django 4.2.13 on 2025-11-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0002_alter_newproduct_bought_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='age',
            field=models.CharField(choices=[('18-29', '18-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60+', 'старше 60')], max_length=5, verbose_name='Ваш возраст'),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='health_issues',
            field=models.TextField(verbose_name='Топ 3 вопроса по эндометриозу, которые интересуют вас больше всего'),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='source',
            field=models.CharField(choices=[('telegram', 'Телеграм'), ('instagram', 'Инстаграм (запрещен в РФ)')], max_length=20, verbose_name='Вы увидели эту анкету у меня в'),
        ),
    ]
